name: CubeVanish
version: ${project.version}
main: net.survivalcube.cubevanish.Cubevanish
api-version: 1.16
authors: [ SlimeDiamond ]
description: SurvivalCube's Vanish plugin
website: https://survivalcube.net/
softdepend: [ProtocolLib]
commands:
  vanish:
    description: Disappear!
    usage: /vanish
    aliases: [v, cv]
  fancyvanish:
    description: Disappear in style
    usage: /fancyvanish <effect>
    aliases: [fv, cfv]
  vanishedplayers:
    description: see all vanished players
    usage: /vanishedplayers
    aliases: [vp]
  joinvanished:
    description: toggle join vanished
    usage: /joinvanished
    aliases: [jv]
permissions:
  survivalcube.vanish:
    default: op
    description: everything
